server:
  port: 10001
  shutdown: graceful
  tomcat:
    #最大连接数
    max-connections: 1000
    #最大等待数
    accept-count: 500

logging:
  level:
    com:
      zhoushengen:
        robot: DEBUG

wechat:
  register: xxx
  ourChatId: xxx
  girlFriendWxid: xxx
  masterWxid: xxx
  chunkSize: 600
  function:
    loginConfirm: false

jenkins:
  token: 1109c24d77d5c8034be4d44c07b3ec62dd

milvus:
  host: 127.0.0.1
  port: 19530
  collection: xxx
  outputField: xxx

openAI:
  auth-token: Bearer sk-xxx
  ## 访问超时时间 单位：秒
  request-timeout: 60

ak:
  baidu: xxx
  juHe:
    fapig: xxx
    todayOnhistory: xxx
    calendar: xxx
    simpleWeather: xxx

proxy:
  confirm: true
  host: 127.0.0.1
  port: 10809

spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 20
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat?useSSL=false&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler #实例名
            instanceId: AUTO #实例编号自动生成
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool #连接池实现类
            threadCount: 10 #线程数量
            threadPriority: 5 #线程优先级
            threadsInheritContextClassLoaderOfInitializingThread: true #配置是否启动自动加载数据库内的定时任务，默认true
